// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/cars/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cars/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cars/[id].put').default>>>>
    }
    '/api/cars': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cars/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cars/index.post').default>>>>
    }
    '/api/cars/presets': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cars/presets.get').default>>>>
    }
    '/api/drivers/:id': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/drivers/[id].put').default>>>>
    }
    '/api/drivers': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/drivers/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/drivers/index.post').default>>>>
    }
    '/api/fuel': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/fuel/index.get').default>>>>
    }
    '/api/fuel/refuel': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/fuel/refuel.post').default>>>>
    }
    '/api/maintenance': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/maintenance/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/maintenance/index.post').default>>>>
    }
    '/api/reports/dashboard': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reports/dashboard.get').default>>>>
    }
    '/api/reports': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reports/index.get').default>>>>
    }
    '/api/users/:id': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id].put').default>>>>
    }
    '/api/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/index.post').default>>>>
    }
    '/api/waybills/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/waybills/[id].get').default>>>>
    }
    '/api/waybills/:id/close': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/waybills/[id]/close.patch').default>>>>
    }
    '/api/waybills': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/waybills/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/waybills/index.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+nitro-server@3.21.2_d_7775f3499a3a49de1df47bee25f090a1/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}