// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12.03.2026, 17:43:44
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/Acer/Desktop/mvp4/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Acer/Desktop/mvp4/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Acer/Desktop/mvp4/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Acer/Desktop/mvp4/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Acer/Desktop/mvp4/plugins/**/*.{js,ts,mjs}","C:/Users/Acer/Desktop/mvp4/composables/**/*.{js,ts,mjs}","C:/Users/Acer/Desktop/mvp4/utils/**/*.{js,ts,mjs}","C:/Users/Acer/Desktop/mvp4/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Acer/Desktop/mvp4/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Acer/Desktop/mvp4/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Acer/Desktop/mvp4/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;